### ISSUE TITLE
Don't compat macOS 12.3

### ISSUE THREAD

**Issue by tianma8023** [zjn0505/adb-alfred#26]
Because macOS 12.3 removed the bundle of Python 2.7 

So the command:
```shell
python xxx
```
causes the error like this:
```shell
/bin/bash: python: command not found
```

## reference
- [Making Python 2 Workflows work on macOS Monterey 12.3 and above](https://www.alfredforum.com/topic/17941-making-python-2-workflows-work-on-macos-monterey-123-and-above/#comments)
- [Python 2 Workflows on macOS Monterey](https://www.alfredapp.com/help/kb/python-2-monterey/)

**Comment by tianma8023** [comment]
The same with: [AlfredWorkflow-Recent-Documents#25](https://github.com/mpco/AlfredWorkflow-Recent-Documents/issues/25)

**Comment by AfzalivE** [comment]
I'm not sure if this PR is wanted but here's the commit with the changes that make it work on macOS 12.3

https://github.com/AfzalivE/adb-alfred/commit/4a95de3ea8079b5c47af174f79518aa84580ab98

**Comment by zjn0505** [comment]
I saw the discussion at deanishe‘s repo. Certainly many python based workflows would be affected.

> I'm not sure if this PR is wanted but here's the commit with the changes that make it work on macOS 12.3
> 
> [AfzalivE@4a95de3](https://github.com/AfzalivE/adb-alfred/commit/4a95de3ea8079b5c47af174f79518aa84580ab98)

I suppose it will break macOS that are not 12.3 to use `/usr/bin/python3`, I haven't updated the OS to check.

I have another workflow locally using the forked alfred-workflow-py3 due to some dependency with py2. I will check it out to see if this workflow can be migrated to alfred-workflow-py3 as well.
